swiftmailer:
        transport:        gmail
        username:         gilgamet04@gmail.com
        password:         31128211Aa
        host:             localhost
        port:             465
        encryption:       ssl
        auth-mode:        login
        spool: { type: 'memory' }
        stream_options:
            ssl:
                allow_self_signed: true
                verify_peer: false
                verify_peer_name: false