vich_uploader:
    db_driver: orm

    mappings:
        portfolio_image:
            uri_prefix: /images/portfolios
            upload_destination: '%kernel.project_dir%/public/images/portfolios'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
